- hosts: master
  become: yes
  tasks:
    - name: Create mount points
      file: path={{ item }} state=directory mode=777 owner=root group=root
      with_items:
        - /data
        - /config

    - name: Mount device with label DATA
      mount:
        path: /data
        src: LABEL=DATA
        fstype: ext4
        state: mounted

    - name: Mount device with label CONFIG
      mount:
        path: /config
        src: LABEL=CONFIG
        fstype: ext4
        state: mounted

    - name: Ensure nfs-kernel-server is present
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - nfs-common
        - nfs-kernel-server

    - name: Copy /etc/exports
      template:
        src: exports.j2
        dest: /etc/exports
        owner: root
        group: root

    - name: Restart nfs server
      service:
        name: nfs-kernel-server
        state: restarted
