- hosts: nodes
  remote_user: ubuntu
  sudo: yes
  tasks:
  - name: Ensure NFS common is installed.
    apt:
      name: nfs-common
      state: installed
      update_cache: yes

  - name: Mount device with path /data
    mount:
      name: /data
      src: {{hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address']}}:/data
      fstype: nfs
      opts: defaults,nobootwait
      state: mounted
  
  - name: Mount device with path /config
    mount:
      name: /config
      src: {{hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address']}}:/config
      fstype: nfs
      opts: defaults,nobootwait
      state: mounted
